version: '3.8'
services: 
  backend:
    build: 
      context: ./restapi
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    restart: always
    environment:
      - REDIS_DB_HOST=redis-server
      - SQLALCHEMY_DATABASE_URI=postgresql://balihotproperty:123@postgres/balihotproperty
    volumes: 
      - "./restapi:/app"
      - "/app/migrations"
    ports: 
      - "192.168.18.109:5001:5000"
    depends_on: 
      - postgres
      - pgadmin4
      - redis-server
  postgres:
    image: "postgres"
    restart: always
    environment: 
      - POSTGRES_DB=balihotproperty
      - POSTGRES_USER=balihotproperty
      - POSTGRES_PASSWORD=123
  pgbackups:
    image: "prodrigestivill/postgres-backup-local"
    restart: always
    volumes:
      - "./restapi/backups:/backups"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=balihotproperty
      - POSTGRES_USER=balihotproperty
      - POSTGRES_PASSWORD=123
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=80
  pgadmin4:
    image: "dpage/pgadmin4"
    ports: 
      - "192.168.18.109:5437:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=oman@balihotproperty.com
      - PGADMIN_DEFAULT_PASSWORD=123
  redis-server:
    image: "redis"
    sysctls:
      - net.core.somaxconn=511
